[package]
name = "qubit-progress"
version = "0.6.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-progress"
description = "Generic progress reporting abstractions for Qubit Rust libraries"
homepage = "https://github.com/qubit-ltd/rs-progress"
documentation = "https://docs.rs/qubit-progress"
readme = "README.md"
keywords = ["progress", "reporting", "status", "stage"]
categories = ["development-tools"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/RUST_CODING_STYLE.md",
    "/RUST_CODING_STYLE.zh_CN.md",
    "/doc/**/user_guide*.md",
    "/examples/**",
    "/resources/**",
    "/src/**",
    "/tests/**",
]

[lib]
name = "qubit_progress"
doctest = true

[features]
default = ["consumer-reporters", "json", "log"]
consumer-reporters = ["dep:qubit-function"]
json = ["consumer-reporters", "dep:serde_json"]
log = ["consumer-reporters", "dep:log"]

[dependencies]
log = { version = "0.4", optional = true }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", optional = true }

qubit-function = { version = "0.16", optional = true }
qubit-serde = { version = "0.4", path = "../rs-serde" }

[dev-dependencies]
serde_json = "1.0"
