[package]
name = "qubit-progress"
version = "0.8.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-progress"
description = "Generic progress reporting abstractions for Qubit Rust libraries"
homepage = "https://github.com/qubit-ltd/rs-progress"
documentation = "https://docs.rs/qubit-progress"
readme = "README.md"
keywords = ["progress", "reporting", "status", "stage"]
categories = ["development-tools"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/doc/**/user_guide*.md",
    "/examples/**",
    "/resources/**",
    "/src/**",
    "/tests/**",
    "/benches/**",
]

[lib]
name = "qubit_progress"
doctest = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }

[features]
default = []
serde = ["dep:serde"]
json-lines = ["serde", "dep:serde_json"]
log = ["dep:log"]

[dependencies]
log = { version = "0.4", optional = true }
qubit-fast-cas = "0.3"
serde = { version = "1.0", features = ["derive", "rc"], optional = true }
serde_json = { version = "1.0", optional = true }


[dev-dependencies]
criterion = { version = "0.8.2", default-features = false }
loom = "0.7"
serde_json = "1.0"

[[bench]]
name = "progress_bench"
harness = false
